name: Build
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          # This combinations doesn't exist
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v4

    - name: "Build and Release"
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.21"
        ldflags: "-X main.version=${{ github.event.release.name }}"
        project_path: "./cmd/editorconfig-checker"

